name: dart_pokemon_core
description: dart_pokemon_core
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dev_dependencies:
  lints: ^1.0.1
  test: ^1.21.1
  mocktail: ^0.3.0

dependencies:
  dio: ^4.0.6
